version: "3"
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    #            target: development
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    # command: npm run serve
    command: >
      ash -c 'npm install; npm run dev'
    # command: sleep infinity # devcontainer のときはこれが必要